<?php
session_start();
if(!isset($_SESSION["login-{$root}"])){?>
    <script>
        location.href='<?=$root?>';
    </script><?php
    exit;
}
if($_SESSION['admin']!=true){
    ?><script>
        history.back();
    </script><?php
    exit;
}
?>